### ISSUE TITLE
А почему не gitbook.com?

### ISSUE THREAD

**Issue by Slavenin** [wunsh/ecto-book-ru#1]
Собственно сабж.

**Comment by jarosluv** [comment]
Спасибо за идею, был план разместить интересные опенсорс репозитории в одном месте. Но может быть для книги действительно будет удобнее Гитбук.

**Comment by Slavenin** [comment]
Как минимум читать и комментировать удобнее там, можно к спорным ментам оставлять комментарии, примерно как в гуглодоке.
